### PR TITLE
UI/API connections for Sign up UI, Login UI and Dashboard UI pages

### PR DESCRIPTION
**Pull request by AtamaZack**
Hello team,
Kindly take some time off your busy schedule and review for me this pull request.
**What is included in this pull request;**
- Sign up JavaScript code refactoring to improve on UI/API connection
- Login JavaScript code refactoring to improve on UI/API connection
- Dashboard UI connections to API by adding a dashboard JavaScript file for the connection
- Refactoring to API codebase to best connection with frontend UI pages
- Added endpoint for getting incidents by incident status type for dashboard incident statistics
- New UI page for adding a new incident to replace independent new red-flag and new intervention UI pages

@nicholus @Rhytah @JamesMudidi @sanya-kenneth @frankopkusianwar @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @v1b3m @mwinel @sebbss

[Click here](https://atamazack.github.io/iReporter-challenge-4/template/sign_up.html) for the hosted application

Thank you.

### CODE REVIEW

**Comment by fodongkara** [comment]
@AtamaZack  have the changes you made to your endpoints affected your documentation? I haven't tested your documentation but I have noticed you made some modifications to your endpoints.

**Comment by AtamaZack** [comment]
Hello @fodongkara ,
Implementing the feedback in the next commits,
Thank you.

**Comment by llwasampijja** [comment]
Hello @AtamaZack , Failed to signup, am getting this error on the UI Error: [object Object] and this in the console:
Failed to load resource: the server responded with a status of 404 ()
2sign_up:1 POST https://i-reporter-challenge-4.herokuapp.com/api/v1/auth/sign_up 400 (BAD REQUEST)

**Comment by AtamaZack** [comment]
@llwasampijja ,
Will have this fixed
Thanks for the review.

**Pull request closed without merging**
